### ISSUE TITLE
cmake policies active: CMP0020 CMP0043

### ISSUE THREAD

**Issue by LawrenceNJU** [CloudCompare/CloudCompare#478] opened 2016-12-04 11:37 UTC
## Current Behavior
When I use CMake to configure CloudCompare, I meet the error "cmake policies active: CMP0020 CMP0043". 

## My Environment
WIndows 10, 
MinGW (GCC 6.1.0)
CMake 3.7.0
Qt 5.6

**Comment by ORNis** [comment] 2016-12-04 12:33
Are you sure you meet an error but not just a warning ?

**Comment by LawrenceNJU** [comment] 2016-12-04 12:47
Thank you very much! 
But when I make, the error is met:
![image](https://cloud.githubusercontent.com/assets/19586476/20866215/b510ce16-ba62-11e6-8f4f-ef0531e1ac3a.png)
How to solve it?

**Comment by dgirardeau** [comment] 2016-12-04 13:09
Looks like an issue with Qt linkage. Are you sure you use the right version of Qt? (target architecture, version of the compiler, etc.)?

Can you show us the Qt5XXX variables in CMake?

**Comment by LawrenceNJU** [comment] 2016-12-04 13:12
Thank you very much, I use qt 5.6 .
![image](https://cloud.githubusercontent.com/assets/19586476/20866334/4796f258-ba66-11e6-9182-2459034cb211.png)

**Comment by dgirardeau** [comment] 2016-12-04 13:14
And are you actually using a 32 bits compiler? You have the choice when configuring the CMake project the first time.

**Comment by LawrenceNJU** [comment] 2016-12-04 13:18
I must use 36 bits compiler?

**Comment by dgirardeau** [comment] 2016-12-04 13:19
No but you are currently trying to link with Qt 5.6 **32 bits**. It only works with a 32 bits comipler.

If you want to compile with a 64 bits compiler (e.g. MinGW), you'll need the 64 bits version of Qt for MinGW.

**Comment by LawrenceNJU** [comment] 2016-12-04 13:23
Thank you very much! I try it.

**Comment by ORNis** [comment] 2016-12-04 20:25
Thank you @LawrenceNJU. Any update?

**Comment by ORNis** [comment] 2016-12-07 16:04
This issue is not confirmed and seems no longer active. I close it for now. Please re-open it if you have more inputs on this.
Thank you.

**Closed by ORNis** 2016-12-07 16:04 UTC
Labels: not_yet_confirmed
