### ISSUE TITLE
Crash loading multiple PLY files

### ISSUE THREAD

**Issue by ghost** [CloudCompare/CloudCompare#393] opened 2016-05-30 09:37 UTC
- Drag and drop a first file (PLY) on a 3D view: the Load PLY dialog appears.
- Drag and drop a second file (PLY) on a 3D view (while the previous Load PLY dialog is already active). A second Load PLY dialog appears
- Accept the first dialog (ok)
- Accept the second dialog (crash)

**Comment by asmaloney** [comment] 2019-02-24 22:18
Cannot reproduce on macOS - does not allow the second drag.

**Comment by tmontaigu** [comment] 2021-02-24 13:40
Closing as the issue is quite old, the OP is a deleted account and I also cannot reproduce the bug either.

**Closed by tmontaigu** 2021-02-24 13:40 UTC
Labels: bug, not_yet_confirmed
