### ISSUE TITLE
Liblas exception - version minor out of range

### ISSUE THREAD

**Issue by tnacsak** [CloudCompare/CloudCompare#1308] opened 2020-08-08 15:33 UTC
I try to open a LIDAR file, with the size of 33MB.
CloudCOmpare drops the following messages:
```
[17:23:40] Liblas exception: 'version minor out of range'
[17:23:42] An error occurred while loading 'merge_all_EOV_EOMA_Ground': the third-party library in charge of saving/loading the file has thrown an exception
```
The file I try to open is attached as zip.
[merge_all_EOV_EOMA_Ground.las.zip](https://github.com/CloudCompare/CloudCompare/files/5045454/merge_all_EOV_EOMA_Ground.las.zip)

CloudCompare version I have 2.11.1 (I tried 2.10.2 before).
It is on MacOS 10.15.5

**Comment by dgirardeau** [comment] 2020-08-23 22:27
Sadly I can't reproduce it on Windows. That may be related to the version of GDAL used on the macOS version? @asmaloney may have an idea?

**Comment by asmaloney** [comment] 2020-08-24 13:30
> That may be related to the version of GDAL...

This is a LAS issue, not GDAL.

The version of the LAS file is likely > 1.3.

**Comment by dgirardeau** [comment] 2020-08-24 17:40
Sorry not GDAL, PDAL!

**Comment by tmontaigu** [comment] 2022-11-13 19:38
Closing as the newer macos binaries are using the PDAL based plugin which is capable of handling files > 1.3,
and will soonᵀᴹ use the new LASZip based plugin

**Closed by tmontaigu** 2022-11-13 19:38 UTC
