### ISSUE TITLE
CloudCompare fails to launch with QXcbConnection error

### ISSUE THREAD

**Issue by msy22** [CloudCompare/CloudCompare#611] opened 2017-10-24 23:53 UTC
## Current Behavior
When launching CloudCompare via desktop icon, nothing will happen and CloudCompare will not load. I.e. no GUI, no error messages or any other indication that it has failed to launch. When launching via commandline with:

    $ cloudcompare.CloudCompare

CloudCompare doesn't load and will instead return this error:

    QXcbConnection: Could not connect to display :0
    Aborted (core dumped)

Trying to launch CloudCompare with `sudo`/as root user returns a slightly different error message:

    mkdir: cannot create directory '/run/user/0': Permission denied
    QXcbConnection: Could not connect to display :0

## Expected Behavior
CloudCompare should start as normal.

## Steps to Reproduce (for bugs)
Simply launching CloudCompare.

## Context/Comments
Having looked around Github and various forums, this seems to be a problem that people have encountered with other programs that use `snap`. So I'm not sure if I should be posting this here or somewhere else. I also realise that this isn't really enough information to debug the problem, so if there is any other diagnostic info I can/should provide, let me know and I will add it.

## Your Environment

* **OS & Version:** Ubuntu 14.04 LTS
* **CC Version:** v2.8.1 (latest)
* **Graphics card:** Intel Haswell Mobile 
* **Qt version:** 5.9.1
* **QMake version:** 3.1
* **Snap version:** 2.28.5

**Comment by dgirardeau** [comment] 2017-10-27 06:09
I don't know much about Linux in general and Snap in particular.

However I know that CC doesn't work well with Intel graphic cards (in fact it's an issue with Qt applications and OpenGL in general). Are there specific drivers for your graphic card that you can install/update maybe?

**Comment by rjanvier** [comment] 2017-10-27 08:34
Thanks for reporting that. 
but like in your thread [here](https://stackoverflow.com/questions/42607918/error-after-installing-packages-with-snap) I think it's not cloudcompare related nor even more related to the way we made the snap package. 
I have no clue on the way to fix this because it feels like you have a very specific setup and I guess the ubuntu community on stackoverflow will find an fix to your problem. Feel free to close the issue once you manage to run the snap and don't hesitate to come back and post more CC related issue on github.

**Comment by msy22** [comment] 2017-10-29 20:39
I had feeling that might be the case. I've post this on StackOverflow and I'll report back if a solution is found. Otherwise, anyone reading this issue at a later data can find the StackOverflow question [here](StackOverflow).

Thanks for your help!

**Comment by msy22** [comment] 2017-11-03 01:30
I can actually get CloudCompare working again by completely uninstalling it and then re-installing it. Uninstalling and then re-installing was one of the first things I tried to solve this issue, but it didn't work then and for some unknown reason worked when I tried it today. However, when launching CloudCompare with

    $ cloudcompare.CloudCompare

It still launches, but I get the error:

    Gtk-Message: Failed to load module "overlay-scrollbar"
    Gtk-Message: Failed to load module "unity-gtk-module" 
    Gtk-Message: Failed to load module "canberra-gtk-module"
    Qt: Session management error: None of the authentication protocols specified are supported
    void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "" under id 134
    void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "" under id 98

I'm not sure if this error message is in any way relevant to the original problem, or a separate issue entirely.

**Comment by rjanvier** [comment] 2018-03-27 07:18
Yes I got those errors. I guess the first 4 errors are related to snap isolation and the last two are are more like warnings. They eventually don't have any impact on the stability of the software.

**Comment by PolarNick239** [comment] 2018-04-10 09:12
I also can't launch ```cloudcompare.CloudCompare``` without sudo:

```
need to run as root or suid
```
And with  ```sudo cloudcompare.CloudCompare``` I get:

```
mkdir: cannot create directory '/home/polarnick/snap/cloudcompare/131/.local': Permission denied
mkdir: cannot create directory '/home/polarnick/snap/cloudcompare/131/.cache': Permission denied
mkdir: cannot create directory '/home/polarnick/snap/cloudcompare/131/.config': Permission denied
Can't create dir /root/Downloads
Can't create dir /root/Templates
Can't create dir /root/Public
Can't create dir /root/Documents
Can't create dir /root/Music
Can't create dir /root/Pictures
Can't create dir /root/Videos
Can't save user-dirs.dirs, failed to create directory
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share' is not a directory
ln: failed to create symbolic link '/home/polarnick/snap/cloudcompare/131/.themes': Permission denied
cp: cannot create directory '/home/polarnick/snap/cloudcompare/131/.local/share': No such file or directory
Directory '/home/polarnick/snap/cloudcompare/131/.local/share/mime/packages' does not exist!
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.cache’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.cache/gio-modules' is not a directory
Unable to open directory /home/polarnick/snap/cloudcompare/131/.cache/gio-modules: Error opening directory '/home/polarnick/snap/cloudcompare/131/.cache/gio-modules': No such file or directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/glib-2.0/schemas' is not a directory
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/glib-2.0/schemas' is not a directory
Error opening directory '/home/polarnick/snap/cloudcompare/131/.local/share/glib-2.0/schemas': No such file or directory
/snap/cloudcompare/131/bin/desktop-launch: line 219: /home/polarnick/snap/cloudcompare/131/.cache/gdk-pixbuf-loaders.cache: No such file or directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/Adwaita' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/DMZ-Black' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/DMZ-White' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/Humanity' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/Humanity-Dark' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/LoginIcons' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: failed to create symbolic link '/home/polarnick/snap/cloudcompare/131/.local/share/icons/default': No such file or directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/hicolor' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/ubuntu-mono-dark' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.local’: Permission denied
ln: target '/home/polarnick/snap/cloudcompare/131/.local/share/icons/ubuntu-mono-light' is not a directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.config’: Permission denied
ln: failed to create symbolic link '/home/polarnick/snap/cloudcompare/131/.config/gtk-3.0/settings.ini': No such file or directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.config’: Permission denied
ln: failed to create symbolic link '/home/polarnick/snap/cloudcompare/131/.config/gtk-3.0/bookmarks': No such file or directory
mkdir: cannot create directory ‘/home/polarnick/snap/cloudcompare/131/.config’: Permission denied
ln: failed to create symbolic link '/home/polarnick/snap/cloudcompare/131/.config/gtk-2.0/gtkfilechooser.ini': No such file or directory
/snap/cloudcompare/131/bin/desktop-launch: line 302: /home/polarnick/snap/cloudcompare/131/.last_revision: Permission denied
No protocol specified
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```

Workaround that works for me:
```
CLOUD_COMPARE_DIR=/snap/cloudcompare/131
LD_LIBRARY_PATH=${CLOUD_COMPARE_DIR}/lib/cloudcompare/:${CLOUD_COMPARE_DIR}/usr/lib/:${CLOUD_COMPARE_DIR}/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH ${CLOUD_COMPARE_DIR}/bin/CloudCompare
```

**Comment by PolarNick239** [comment] 2018-04-10 09:39
Ubuntu 16.04 LTS, ```dpkg -l | grep snapd``` shows 2.0.3, NVidia 390.25 (Titan X Maxwell + GTX 1080), single monitor. And with workaround CloudCompare works great without any errors in terminal.

Firstly I tried ```snap install cloudcompare``` but got ```error: access denied (snap login --help)```, so I tried ```sudo snap install cloudcompare``` and it worked Ok, but after that I couldn't launch cloudcompare.

It seems that snap should be used after ```snap login```, but I already workarounded the problem with manual LD_LIBRARY_PATH. I wrote about this workaround here for those who also will miss ```snap login``` :)

**Comment by PolarNick239** [comment] 2018-04-10 09:57
In clean virtual machine with Ubuntu 16.04.1 LiveCD (via try Ubuntu):
```
snap --version
# snap  2.0.10
# snapd 2.0.10
sudo apt update
sudo apt install --only-upgrade snapd
snap --version
# snap  2.29.4.2
# snapd 2.29.4.2
snap install cloudcompare
cloudcompare.CloudCompare
# cannot create lock directory /run/snapd/lock: Permission denied
```

**Comment by rjanvier** [comment] 2018-04-10 09:57
sudo snap install cloudcompare

**Comment by PolarNick239** [comment] 2018-04-10 10:08
Thanks, my reaction was the same, and ```sudo snap install cloudcompare``` executed successfully, but after that cloudcompare.CloudCompare couldn't be run with and without sudo, with errors posted here - https://github.com/CloudCompare/CloudCompare/issues/611#issuecomment-380030540

But I was able to run cloudcompare with explicit LD_LIBRARY_PATH (even without sudo).

**Comment by PolarNick239** [comment] 2018-04-10 10:26
I reported problem described in https://github.com/CloudCompare/CloudCompare/issues/611#issuecomment-380043654 here - https://forum.snapcraft.io/t/test-failures-with-cannot-create-lock-directory-run-snapd-lock/390/41 

Because this seems to be easily reproducable case on clean OS with the most actual snap. And it looks for me like snap generic problem.

**Comment by rjanvier** [comment] 2018-04-10 11:36
It's clearly not reproducible on a clean os, since I just run it perfectly on a fresh unbuntu **install** of 16.04.4 on virtualbox. The issue here is that you maybe use a livecd and *not* a fresh install or maybe the partial  update  (--only-upgrade snapd) or maybe 16.04.1

**Comment by PolarNick239** [comment] 2018-04-10 12:27
Oh, nice to hear. Any way I am able to launch cloudcompare, so I don't have issues.

**Closed** 2018-04-10 18:55 UTC
Labels: Linux

**Comment by w4rlock999** [comment] 2019-05-28 08:26
I resolve this with installing qt5-default on ubuntu
"sudo apt-get install qt5-default"

**Comment by i7sharath** [comment] 2019-06-27 00:29
I was able to resolve this with upgrading snapd 
snapd --version ( upgrade from 2.38 to 2.39 ) works for me
