### ISSUE TITLE
pcl plugin does not consider sensor viewpoint when loading .pcd-files

### ISSUE THREAD

**Issue by Tones29** [CloudCompare/CloudCompare#522] opened 2017-03-30 14:20 UTC
## Current Behavior
 * Load different pcd files, that contain all the same point coordinates, but different viewpoints
* All points are displayed in the some position, the viewpoint in the .pcd-file is not considered

## Expected Behavior
 * Points should be positioned and oriented according to viewpoint

## Steps to Reproduce (for bugs)
Test files:
[pcltest.zip](https://github.com/CloudCompare/CloudCompare/files/882595/pcltest.zip)

## Your Environment
* OS & Version: ubuntu 16.04, 64 bit
* CC Version: 2.9.beta
* Graphics card: Notebook internal

**Comment by luca-penasa** [comment] 2017-04-02 18:00
I'll check this issue. If I remember well the PCL plugin has minimum support for reading the viewpoint. I am not even sure if ordered point clouds are fully supported. 
So you were expecting to  apply a transform to the viewport and see the points transformed as well?
I am not sure but I think that if you want to see the points roteted and translated in PCL you have to apply the same transform to the points themselves. If I am not wrong (could be) the coordinates stored in a PCD file are expected to be absolute and not relative to the viewpoint (?)
I'll investigate this...
Luca

**Comment by Tones29** [comment] 2017-04-03 08:32
Hi Luca,
thanks for having a look into this. The idea behind the VIEWPOINT argument in pcd files is, that you can transform all points without having to re-calculate each point. So the coordinates stored in the pcd file are always relative to the view point. You can check this for example, if you open multiple of the test files I posted above with the `pcl_viewer`. In the test files, the coordinates are always the same, but the viewpoint differs. This should be considered when loading and saving pcd files from CloudCompare. I am not very familiar with CloudCompare, but if such a viewpoint concept doesn't exist, it might be best to transform the coordinates directly when loading from pcd and save the coordinates always with the identity viewpoint.
Best, Andi

**Comment by luca-penasa** [comment] 2017-04-03 16:25
Thank you Andi, 
So the points coordinates are meant to be relative to the viewpoint. Although it would make totally sense, I tried to look into the documentation of pcl but they don't give any information about it. I mean it is totally feasible to modify the code to transform the point too once loaded, but I would like to know what was the intended use/behaviour for the viewpoint in PCD files. Have you found any discussion or documentation about it? -  I guess anybody can do whatever they want in the PCD file... depending on their own code.

I think the easiest way would be to have a dialog asking if CC should consider points as absolute coords or relative to the viewpoint. That would be a good way I think! What do you think?

Luca

**Comment by Tones29** [comment] 2017-04-03 20:08
Hi Luca,
that is fine for me. Do you have someone we can contact in the active pcl community?
Andi

**Comment by luca-penasa** [comment] 2017-04-04 08:15
I'll write an email to the ML and see what they say about it.
Luca

**Comment by luca-penasa** [comment] 2017-04-04 08:32
here it is: http://www.pcl-users.org/Intended-behavior-of-viewpoint-in-PCD-files-td4044240.html

**Comment by meiler-inunum** [comment] 2021-11-30 13:09
I can confirm that this is an issue. I'm using version 2.12-alpha, which ignores the viewpoint information in the pcd header.

Best,
Michael

**Comment by dgirardeau** [comment] 2021-12-04 17:35
Ok that should be fixed now! (hopefully I applied the rotation matrix in the right direction ;): 05ad11a517f371d854d06219453f8a48b6bc7903

I also added support for structured PCD files by the way (so as to be able to compute robust normals).

(the Windows 2.12.beta version online has been updated)

D'ont hesitate to reopen this issue if you observe something strange (but I'll probably need some example files in this case)

**Closed by dgirardeau** 2021-12-04 17:35 UTC

**Comment by meiler-inunum** [comment] 2021-12-06 06:39
Awesome! 

The viewpoint seems to be applied correctly.

**Comment by tschuette22** [comment] 2023-08-09 09:17
Sorry to bring this issue back up, but I noticed an important difference when loading .pcd data compared to e.g. las data, when we have a large offset (viewpoint is e.g. in UTM coordinates). In that case the plugin will transform all points into the viewpoint, without considering to shift the point cloud, resulting in loss of accuracy. 

In comparison, if I load a .las file with such data, CC will ask me if I want to shift the Cloud to avoid the accuracy loss. This would be a valuable improvement for this type of data and might also speed up the loading process, if we do not have to transform every single point.

I had the described behaviour on CC v2.13alpha.

**Comment by dgirardeau** [comment] 2023-09-16 12:49
Sorry for the late reaction. I checked the code, and I saw that the PCL format relies on 32bits floating point values (or at least CC only handles this format). Therefore, there's no need to apply a Global Shift.

Another way to put it is that applying a Global Shift at that point would be too late ;)
