### ISSUE TITLE
Version is not displayed in the 'About' dialog

### ISSUE THREAD

**Issue by ryanthara** [CloudCompare/CloudCompare#1415] opened 2021-03-05 13:14 UTC
**Describe the bug**

The current version is not shown in the 'About' dialog.

**How to reproduce**

Open the 'About' dialog.

**Expected behaviour**

Show the current version (major.minor.bugfix) in the bottom of the dialog window.

<img width="712" alt="Bildschirmfoto 2021-03-05 um 14 12 46" src="https://user-images.githubusercontent.com/7117072/110120086-de30dd00-7dbc-11eb-8d4a-9b6cfcc2db7e.png">

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.11.1 (Anoia)
 - OS & Version: macOS Big Sur 11.2.2
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by tmontaigu** [comment] 2021-03-05 14:37
I would say it is likely a problem caused by the  Qt version used in the CloudCompare macOs App being outdated for macOs 11.2.2

Also are you using a mac with the new Apple Silicon processor ?

**Comment by ryanthara** [comment] 2021-03-05 14:40
> I would say it is likely a problem caused by the Qt version used in the CloudCompare macOs App being outdated for macOs 11.2.2

Ok, then a newer version would be great. :)

> Also are you using a mac with the new Apple Silicon processor ?

Unfortunately no.

**Comment by tmontaigu** [comment] 2021-03-05 19:59
I can reproduce on a mac with Big Sur 11.3 beta

**Comment by dgirardeau** [comment] 2021-03-06 09:52
I tried to fix this issue by explicitly forcing the default text color to black: 2ae7b490d9b07cdc2544b1dd117075cc9189f7ed

I'll wait for your feedback to see if this helps?

**Comment by ryanthara** [comment] 2021-03-07 20:33
> I tried to fix this issue by explicitly forcing the default text color to black: [2ae7b49](https://github.com/CloudCompare/CloudCompare/commit/2ae7b490d9b07cdc2544b1dd117075cc9189f7ed)

I think it could come from the 'dark mode' on macOS Big Sur (11.2.2 here).  
 
> I'll wait for your feedback to see if this helps?

This is how it looks in the 'light mode'.

<img width="712" alt="Bildschirmfoto 2021-03-07 um 21 27 00" src="https://user-images.githubusercontent.com/7117072/110253711-23573980-7f8c-11eb-8440-31c950e38c14.png">

Should the behavior of color selection not done by Qt functions automatically, instead of hard coding?

**Comment by tmontaigu** [comment] 2021-06-06 07:51
This should be fixed by #1437

**Closed by tmontaigu** 2021-06-06 07:51 UTC
Labels: MacOS, bug
