### ISSUE TITLE
Global Shift not applied correctly 2.12.2

### ISSUE THREAD

**Issue by laurieuasinc** [CloudCompare/CloudCompare#1659] opened 2022-06-08 17:16 UTC
Hi all.  This was previously reported, but closed with a workaround.  But it is a bug and should be fixed.

There is a persistent problem with 2.12.2. When opening files, if you click No to the suggested offset, it applies the default anyway. If you explicitly type 0,0,0, it is positioned correctly. 

To test, open two coregistered files, selecting No for the shift. This SHOULD use no shift.  They will not align (assuming bounds are different). If you do that again, but type 0,0,0, they will load correctly. This was found and reproduced in 2.12.2. It does not exist in 2.11.0 which was used as a back check.

Also, it does not KNOW that it applied the shift. It shows 0,0,0 as the shift even though it has applied the defaults.

**Comment by dgirardeau** [comment] 2022-06-13 22:13
Good catch. Even though it's generally a bad idea to not apply a Global Shift, the intended behavior is of course to not (silently) apply a Global Shift if the user has clicked on cancel ;).

This has been fixed in the 2.12.3 version (and in the latest 2.13.alpha release as well)

See 160d7a3660912ee2aeea32e4e49b1c94adfe481e

**Closed by dgirardeau** 2022-06-13 22:13 UTC
Labels: bug
