### ISSUE TITLE
CMake complains about cgal version for cgal 4.10

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#532] opened 2017-06-03 16:17 UTC
I'm on archlinux, despite having CGAL 4.10 cloudcompare cmake complains about cgal being less than 4.3
`CMake Error at CC/CGALSupport.cmake:9 (message):
  CC Lib requires at least CGAL 4.3`

**Comment by luca-penasa** [comment] 2017-06-05 08:01
I am on archlinux too... no problem with cgal. 
with one of the latest updates they fixed a bug in the cmake files for cgal. Thus you might want to check if everything is updated on your system, cause it might be the cause...

I have cgal 4.9.1-2 on my system. could you check this?

Luca

**Comment by bartoszek** [comment] 2017-06-21 13:42
With cgal 4.9.1-2 works fine, but with 4.10-1 same error message.
Looks like same strange issue with double digit minor number in version comparison. Have no idea how to fix it, just remove the test https://aur.archlinux.org/cgit/aur.git/tree/cgal.patch?h=cloudcompare-git

**Comment by dgirardeau** [comment] 2017-07-15 13:35
I believe it's fixed now ;)

Thanks for the feedback.

**Closed by dgirardeau** 2017-07-15 13:35 UTC
