### ISSUE TITLE
picking mode cannot turn back to point picking after extractsection

### ISSUE THREAD

**Issue by StOriJimmy** [CloudCompare/CloudCompare#886] opened 2019-03-29 07:43 UTC
After we end the SectionExtraction tool, the picking mode cannot be activated in 3d point picking. And if we minimize the window then maximize it again, the 3d point picking mode is back. It seems that the m_activeGLWindow is nullptr after the 2D picking mode is deactivated.

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Click on a point cloud
2. Open 'SectionExtractionTool'
3. Click on 'cancle'
4. Click on the same point cloud
5. Open "Point picking Tool"
6. Click on the point cloud to select a single point
7. ERROR: the select mode is still ENTITY_PICKING

same error happens to track polyline 

**Your environment**
 - CC Version (or git hash/tag): 2.10.2
 - OS & Version: windows 10, build 1903
 - Graphics card: nvdia M620
 - Qt Version (if compiling): qt 5.10.0

**Comment by dgirardeau** [comment] 2019-03-29 10:17
Hum, I can't reproduce this issue on my side. When I leave the section extraction tool I do have the 'ENTITY_PICKING' mode enabled (but that's normal as it's the default mode). And then when I enter the Point Picking tool (you don't need to select a cloud by the way - but I did to follow your protocol), I end in the 'POINT_PICKING' mode.

**Comment by StOriJimmy** [comment] 2019-03-29 10:27
Thanks for your reply! It is normal in debug status, the window switches between the debug window and the program window, which reactivated the glwindow. I will try using other computers again. Thanks again!

**Comment by StOriJimmy** [comment] 2019-03-29 10:28
Thanks for your reply! It is normal in debug status, the window switches between the debug window and the program window, which reactivated the glwindow. I will try using other computers again. Thanks again!

**Comment by dgirardeau** [comment] 2019-03-29 11:01
Yes it's better to use two screens when debugging with Visual Studio.

**Comment by tmontaigu** [comment] 2019-03-29 11:44
I think i was able to reproduce the issue: https://imgur.com/a/XoCctLi

After canceling the section extraction tool, the point picking tool can't select points unless I minimize the window

**Comment by StOriJimmy** [comment] 2019-03-29 12:01
Yes, that is exactly the problem I encountered. I traced the code and found out that after canceling the section extraction tool, togglePickingMode of ccPickingHub cannot be called inside the function addListener.

**Comment by asmaloney** [comment] 2019-03-29 17:08
I am able to reproduce this on macOS as well.

I found a couple of oddities with signals, but neither one fixes this problem.

**Comment by dgirardeau** [comment] 2019-03-30 23:32
Okay I finally found the bug! It's fixed now: 19ef8b62d23e68899bccc28e22cf53028c2f9c08

Thanks for the feedback.

**Closed by dgirardeau** 2019-03-30 23:32 UTC
Labels: bug

**Comment by asmaloney** [comment] 2019-03-30 23:58
Nice work!

(Did you mean to leave all that debug stuff in that commit?)

**Comment by StOriJimmy** [comment] 2019-03-31 00:13
Thanks for your brilliant contribution!

**Comment by dgirardeau** [comment] 2019-03-31 09:43
@asmaloney Yes, you can't debug this part with the debugger (as it makes the context change each time a break point is triggered) and I don't want to rewrite this code in the future ;)
