### ISSUE TITLE
Exporting .las/.laz omits geokeys 

### ISSUE THREAD

**Issue by JasonHagon** [CloudCompare/CloudCompare#1008] opened 2019-11-25 12:15 UTC
Thank you for this amazing tool! 

When saving a .las or .laz file which has been imported and edited, the resulting file appears to not have saved the projection information. 

1. Import a .laz file which has been produced using photogrammetry software and has a projection assigned (verified by using lasinfo) 
2. Edit the file in any way. e.g. subsample. 
3. Save as .las/.laz
4. The file no longer has the GeoKeyDirectoryTag

This issue was addressed in another thread (https://github.com/CloudCompare/CloudCompare/issues/515)  and seemed to be solved using a different version of CC. I am using v2.10.2. 

The expected behaviour would be that the file retains the projection information. 

Environment
CC: version 2.10.2
OS: Windows 10 
Graphics card: Nvidia 960m

Thanks, 
Jason.

**Comment by dgirardeau** [comment] 2019-11-25 18:39
Indeed, since then we changed the 3rd party library that loads the LAS files (we now use PDAL). I guess this feature has not been maintained?

**Comment by tmontaigu** [comment] 2019-11-25 19:10
The code exists, but does not seem to work properly 

https://github.com/CloudCompare/CloudCompare/blob/2b258bdcc506bb4f02deb25c1ef3dbf76e60b826/plugins/core/IO/qPDALIO/src/LASFilter.cpp#L1329

https://github.com/CloudCompare/CloudCompare/blob/2b258bdcc506bb4f02deb25c1ef3dbf76e60b826/plugins/core/IO/qPDALIO/src/LASFilter.cpp#L592

**Comment by JasonHagon** [comment] 2019-11-26 11:55
Thanks for the information. Is this something that is possible to fix, or would the alternative be to use a version that doesn't use PDAL?

**Comment by tmontaigu** [comment] 2019-11-26 12:00
Using the latest CloudCompare available to download (2.11.alpha), I get the same problem
However using my compiled version of current master branch with PDAL 2.0.1 I do not have this problem

**Comment by JasonHagon** [comment] 2019-11-26 12:55
Ok, thanks for the update.

**Comment by JasonHagon** [comment] 2019-11-27 10:12
@tmontaigu I had a look at compiling a version using PDAL 2.0.1, however, I was not very successful (that process is completely new to me). Following the instructions, CMake was not able to find Visual Studio "  could not find any instance of Visual Studio". Do you have any recommendations for the best workflow to follow to compile CC with the newer version of PDAL? Thanks.

**Comment by dgirardeau** [comment] 2019-11-27 23:25
Ok on my side I updated PDAL (to last Friday's version ;) as well as LASzip (on which PDAL depends to decode laz files, just in case). I tested with one LAS file with SRS and it seems to work.

Can you test it on your side? (it's the latest 2.11 alpha **non stereo** version available on CC's website)

**Comment by JasonHagon** [comment] 2019-12-01 20:50
Hello, I downloaded 2.11 alpha, but I seem to get the same results as before. Please see screengrab 1 which is from the original las file with information exported from lasinfo & 2, after the same cloud has been opened and saved in CC2.11 alpha.
![Screengrab 1](https://user-images.githubusercontent.com/58173128/69920146-2e174a80-147c-11ea-85cd-26e046e6a43d.JPG)
![Screengrab 2](https://user-images.githubusercontent.com/58173128/69920148-32dbfe80-147c-11ea-92dc-c75c5d9ab001.JPG)

**Comment by dgirardeau** [comment] 2019-12-01 21:21
@tmontaigu  These "geokeys" seem to be saved as VLR. I guess it's different from 'SpatialReference' saved in the header?

**Comment by tmontaigu** [comment] 2019-12-01 21:39
Yes it's normal , in the LAS file format, there is no spetial storage for spatial reference systems.
They are stored in the VLR part of the file, and the the way the spatial reference system are are stored in VLRs is defined in the LAS standard as a combination of Geotiff key for LAS version < 1.4 or Well Known Text for LAS >= 1.4
(I hope i'm clear )

In CC what we do is ask for the SRS it could undertsand from the LAS file's VLR and store it (as proj for string if i'm not wrong) to restore it when saving (pdal then retranslate the proj4 string to geotiff keys).

What must be happenning for the file that does not work is that PDAL does not understand the SRS when reading the geokeys so it gives us nothing, so we do not have any SRS to save.
Or maybe PDAL  gives us a SRS string but fails to retranslate it to geokeys vlr but that would be strange.

@JasonHagon when reading the file with the srs, does CC in the log console shows something like '[LAS] Spatial Reference: None" ?

**Comment by tmontaigu** [comment] 2019-12-01 22:43
I tried the the version on the website and the problem still exists
When loading the file there is a log message: `[LAS]: Spatial Reference: None`, however the same file 
with my compiled version does print `[LAS]: Spatial Reference: +proj=lcc+laz_0=45+lon...`

**Comment by JasonHagon** [comment] 2019-12-02 06:16
Yes, with CC 2.11 alpha the log message on import of the cloud with the keys is: 

[06:12:16] [LAS] Spatial reference: None

**Comment by dgirardeau** [comment] 2019-12-04 15:35
Can one of you share a failing file with me then? (admin [at] cloudcompare.org)

**Comment by JasonHagon** [comment] 2019-12-23 08:14
Hello @dgirardeau sorry for the delayed response. I sent an example .las file to admin@cloudcompare.org, but it hasn't been downloaded. should I resend to a different address?

**Comment by dgirardeau** [comment] 2019-12-23 08:19
I am in a place with a bad internet connection. I failed to download the file several time. It should be better at the end of the week. You can send a new link at that time?

**Comment by JasonHagon** [comment] 2019-12-23 08:20
That's absolutely fine, I will send again on the 27th. Thanks again

**Comment by dgirardeau** [comment] 2019-12-30 09:23
Now I can download big files again ;)

**Comment by JasonHagon** [comment] 2019-12-30 14:28
Ok, I have sent a sample .las file. Thanks for the update.

**Comment by JasonHagon** [comment] 2020-01-17 13:28
Hello, @dgirardeau I was wondering if you had managed to download the .las file?

**Comment by dgirardeau** [comment] 2020-01-17 13:51
Yes. And I had another file with the same issue from @tmontaigu. But sadly I couldn't find a good reason why PDAL is not extracting the information (this is why CC can't restore it at saving time).

We'll have to report this to PDAL now (even though I hoped I had more time to test on my side, just to confirm that the issue doesn't come from our side ;)..

**Comment by JasonHagon** [comment] 2020-01-17 14:05
OK, thanks for taking a look. As a workaround, I have been assigning the projection successfully using las2las if anyone is having the same issue and looking for a solution.

**Comment by dgirardeau** [comment] 2020-01-21 21:31
Okay, back to this issue.

I realized that PDAL is actually loading some SRS info:

```LOCAL_CS["RGF93 / CC45",GEOGCS["RGF93",DATUM["unknown",SPHEROID["unretrievable - using WGS84",6378137,298.257223563],TOWGS84[0,0,0,0,0,0,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],AUTHORITY["EPSG","3945"],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]```

And strangely, when we ask PDAL is the corresponding SpatialReference object is valid or not, the result is 'false' (not valid ;).

And if I force the conversion to Proj.4 string (as it's done currently in the code), it returns a null string...

This is why the SRS is lost in the process anyway.

Any idea what happens? (I'm not the projection expert here)

**Comment by dgirardeau** [comment] 2020-01-21 22:15
Ok, I avoided the issue by simply testing if the SRS was 'not empty', and retrieving the WKT string, instead of the Proj.4 equivalent. See the latest commit (or 2.11.alpha - **non stereo** - online version).

**Comment by tmontaigu** [comment] 2020-01-22 15:35
I think I may have found the root cause:

I tried CC with the latest commit and in the log console, the WKT printed was not the same as expected.
Moreover when saving the file and reading it back the WKT would change

I had :
`LOCAL_CS["RGF93 / CC45", AUTHORITY["EPSG", "3945"]`  
instead of what I expected: https://spatialreference.org/ref/epsg/3945/prettywkt/
And when saving then reading the saved file the WKT became:
`LOCAL_CS["RGF93 / CC45", UNIT["metre",1,AUTHORITY["EPSG", "9001"]]]`


In my terminal, I had a log messages  
```shell
proj_create_from_database: Cannot find proj.db
(readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: Cannot find proj.db
```


A quick research showed me that proj4 expects to find a `proj.db` file, it can find it if the `PROJ_LIB` environment variable is set to the dir where `proj.db` is.

So i did `$env:PROJ_LIB = C:\ProgramData\Miniconda3\envs\raster\Library\share\proj"` as  this is where my conda environment stored the proj.db file.
And now, when using the latest commit, the SRS is as expected or when using a commit where we get the srs.proj4() the proj4 string is a valid one.

**Comment by dgirardeau** [comment] 2020-01-22 19:52
So you mean that even if we store the 'wkt' string in the meta-data and write it back at export time, its content will be changed?

Should we maybe ship the proj.db file with CloudCompare? Is there a way to specify its path at runtime? (I remember the CPLPushFinderLocation method, not sure it works for this db file).

**Comment by tmontaigu** [comment] 2020-01-23 11:33
> So you mean that even if we store the 'wkt' string in the meta-data and write it back at export time, its content will be changed?

It seems yes, with the latest CC you uploaded i do get 
`LOCAL_CS["RGF93 / CC45",GEOGCS["RGF93",DATUM["unknown",SPHEROID["unretrievable - using WGS84",6378137,298.257223563],TOWGS84[0,0,0,0,0,0,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],AUTHORITY["EPSG","3945"],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]`
when reading the original file, then when I save it to read the saved file I get:
`LOCAL_CS["RGF93 / CC45", UNIT["metre",1,AUTHORITY["EPSG", "9001"]]]`

Also when using `pdal info` on the newly saved file I get an error:
```Shell
>pdal info 'C:\Users\t.montaigu\Desktop\las_with_srs - Cloud.las'
PDAL: Geometry::transform() failed.  NULL source SRS.
```

And when using my CC clone I get 
`PROJCS["RGF93 / CC45",GEOGCS["RGF93",DATUM["Reseau_Geodesique_Francais_1993",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6171"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4171"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",44.25],PARAMETER["standard_parallel_2",45.75],PARAMETER["latitude_of_origin",45],PARAMETER["central_meridian",3],PARAMETER["false_easting",1700000],PARAMETER["false_northing",4200000],AUTHORITY["EPSG","3945"],AXIS["X",EAST],AXIS["Y",NORTH]]` both times

> Should we maybe ship the proj.db file with CloudCompare? Is there a way to specify its path at runtime? (I remember the CPLPushFinderLocation method, not sure it works for this db file).

I think we should ship and see if that actually works. The PROJ docs explain how their [resource files 
are looked for](https://proj.org/resource_files.html#where-are-proj-resource-files-looked-for).

The easiest way might probably be to follow this

> On Windows, the ..\share\proj\ and its contents are found automatically at run-time if the installation respects the build structure. That is, the binaries and proj.dll are installed under ..\bin\, and resource files are in ..\share\proj\.

So changing the organisation of CC's install folder to be like this.

```
└───CloudCompare
    ├───bin
    │   │ all dll & .exe
    │   ├───imageformats
    │   ├───platforms
    │   ├───plugins
    │   └───shaders
    │       ├───Bilateral
    │       └───ColorRamp          
    └───share
        └───proj <- proj.db + all other proj resource files in this folder
                 
```
But then we would have to test on Linux & MacOs how to make things work.

**Comment by WargodHernandez** [comment] 2020-04-10 22:40
Is this still an issue? #1024 was merged and listed as fixes this

**Comment by tmontaigu** [comment] 2020-04-10 23:19
Yes, this issue was mistakenly tagged in the PR and its not related to this one

**Comment by tmontaigu** [comment] 2022-11-13 19:40
Closing as the new plugin #1688 should solve this issue

**Closed by tmontaigu** 2022-11-13 19:40 UTC
Labels: bug
