### ISSUE TITLE
CCConst.h:43:40: error: ‘(1.8e+2 / 3.1415926535897931e+0)’ is not a constant expression

### ISSUE THREAD

**Issue by swiss-knight** [CloudCompare/CloudCompare#848] opened 2019-02-19 14:41 UTC
I'm trying to compile CC from sources on Ubuntu 18.04 and I finally encountered this error:

```
In file included from /opt/CloudCompare/CC/include/FastMarching.h:23:0,
                 from /opt/CloudCompare/CC/include/FastMarchingForPropagation.h:24,
                 from /opt/CloudCompare/CC/src/AutoSegmentationTools.cpp:22:
/opt/CloudCompare/CC/include/CCConst.h:43:40: error: ‘(1.8e+2 / 3.1415926535897931e+0)’ is not a constant expression
 constexpr double CC_RAD_TO_DEG = (180.0/M_PI);
                                  ~~~~~~^~~~~~
/opt/CloudCompare/CC/include/CCConst.h:46:39: error: ‘(3.1415926535897931e+0 / 1.8e+2)’ is not a constant expression
 constexpr double CC_DEG_TO_RAD = (M_PI/180.0);
                                  ~~~~~^~~~~~~
CC/CMakeFiles/CC_CORE_LIB.dir/build.make:62: recipe for target 'CC/CMakeFiles/CC_CORE_LIB.dir/src/AutoSegmentationTools.cpp.o' failed
make[2]: *** [CC/CMakeFiles/CC_CORE_LIB.dir/src/AutoSegmentationTools.cpp.o] Error 1
CMakeFiles/Makefile2:987: recipe for target 'CC/CMakeFiles/CC_CORE_LIB.dir/all' failed
make[1]: *** [CC/CMakeFiles/CC_CORE_LIB.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

## Your Environment
* CC Version: master from sources
* OS & Version: Ubuntu 18.04 64 bit
* Graphics card: On CPU (Intel)
### Other relevant details about the environment: 
* gcc : 7.3.0
* cmake suite: 3.13.20181205

Here is the output log of `cmake-gui` before build:

```
cmake policies active:
cmake policies active:
__cplusplus is 201103
  --> Do not link with Boost.Thread
Boost version: 1.68.0
Boost include dirs: /usr/local/include
Boost libraries:    
Build type: Release
USING CXXFLAGS = '-std=c++17 -std=c++11 -fPIC -std=c++11 -fPIC -O3 -DNDEBUG'
USING EXEFLAGS = ' '
Targetting Unix Makefiles
Using /usr/bin/c++ compiler.
Requested component: Core
Boost version: 1.68.0
Found the following Boost libraries:
  thread
  system
  chrono
  date_time
  atomic
Requested component: MPFR
Requested component: GMP
OpenMP found
OpenMP found
Eigen found (include: /usr/include/eigen3, version: 3.3.4)
Boost version: 1.68.0
Found the following Boost libraries:
  system
  filesystem
  thread
  date_time
  iostreams
  serialization
  chrono
  atomic
  regex
FLANN found (include: , lib: flann;flann_cpp)
FLANN found (include: , lib: flann;flann_cpp)
The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
looking for PCL_COMMON
looking for PCL_KDTREE
looking for PCL_OCTREE
looking for PCL_SEARCH
looking for PCL_SAMPLE_CONSENSUS
looking for PCL_FILTERS
looking for PCL_2D
looking for PCL_GEOMETRY
looking for PCL_IO
looking for PCL_FEATURES
looking for PCL_ML
looking for PCL_SEGMENTATION
looking for PCL_VISUALIZATION
looking for PCL_SURFACE
looking for PCL_REGISTRATION
looking for PCL_KEYPOINTS
looking for PCL_TRACKING
looking for PCL_RECOGNITION
looking for PCL_STEREO
looking for PCL_APPS
looking for PCL_CLOUD_COMPOSER
looking for PCL_MODELER
looking for PCL_POINT_CLOUD_EDITOR
looking for PCL_OUTOFCORE
looking for PCL_PEOPLE
CMake Warning (dev) at plugins/core/qPCL/PclUtils/CMakeLists.txt:4 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PCL_ROOT is set to:

    /usr/local

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.13/Modules/FindOpenGL.cmake:272 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  plugins/core/qPCV/CMakeLists.txt:11 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at plugins/core/qRANSAC_SD/RANSAC_SD_orig/CMakeLists.txt:5 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Configuring done
Generating done
```

In addition, I don't know which path has to be set in the `QT5_ROOT_PATH` variable ? It seems it's a relative path from the build local Cloudcompare git directory...

**Comment by asmaloney** [comment] 2019-02-19 16:06
Duplicate of #835

This is a [CGAL](https://github.com/CGAL/cgal/issues/3180) issue.

For me (on macOS) `QT5_ROOT_PATH` isn't set. I set `QT_QMAKE_EXECUTABLE` and everything else flows from that. Maybe it's the same on Linux?

**Closed by asmaloney** 2019-02-19 16:06 UTC
Labels: Linux

**Comment by swiss-knight** [comment] 2019-02-19 16:28
The 'QT_QMAKE_EXECUTABLE' flag doesn't exist on my system.
