### ISSUE TITLE
2.6.1 OS X - graphic and location bug when selecting points

### ISSUE THREAD

**Issue by mankoff** [CloudCompare/CloudCompare#223] opened 2015-07-28 17:27 UTC
The following issues do not exist in 2.6.0.

1) When selecting a point, a point far from where I click is selected
2) point size cannot be changed either by the easy-access "+-" graphics in the main window, or by selecting the vertices and changing the "Point Size" dropdown menu
3) When selecting a point, the information isn't drawn on screen correctly. Attached screenshot shows the point selecting window, and the x,y,z text are in different locations (text is overlaying right-most section of the cloud).

Note item 1) above - I clicked a very different point than where the red line indicates.

<img width="1788" alt="capture d ecran 2015-07-28 a 13 24 00 -04 00" src="https://cloud.githubusercontent.com/assets/145117/8938375/4cec98c2-352c-11e5-8621-c9e32732856e.png">

**Comment by asmaloney** [comment] 2015-07-28 17:46
@mankoff What version of OS X are you using?

This could be a problem with moving from Qt4 (which was used for 2.6.0) to Qt5 (which was used for 2.6.1).

@dgirardeau Might have some thoughts if it was a bug in CC itself?

Once we're getting 2.6.2 together I'll fire you a build to try out.

Thanks for the report.

**Comment by mankoff** [comment] 2015-07-28 17:47
OS X 10.10.4. I'm happy to test next beta.

**Comment by cloudcompare** [comment] 2015-07-28 20:17
Hi guys,

This is not a know bug. But it's clear that Qt 5 caused a lot of issues (especially with OpenGL).

Can you disable the 'Use OpenGL for picking' option in the Display settings? (bottom of the 'Other display options' tab).

**Comment by mankoff** [comment] 2015-07-28 20:31
That open was unchecked, and picking was strange.
I checked it. Behavior the same
I unchecked it. Unable to pick anything.

I tested this 5 times. If checked, picking is offset as initially described. If unchecked I cannot pick at all. This makes me think maybe it was enabled at first but the box check did not match that state.

Picking hard regardless since point size cannot be increased.

**Comment by cloudcompare** [comment] 2015-07-28 20:33
Hum, not good ;)

I definitely think Qt 5 is the cause if even the +/- buttons can't be clicked.

Personnally I will compile the next Windows version with Qt 4 but I don't know if it will be possible for the MacOS version?

**Comment by asmaloney** [comment] 2015-07-28 20:51
Qt5 fixes so many issues with 10.10 - UX and otherwise - that going back might just open up a different set of problems.  (I've moved my own work - and therefore my dev environment - to Qt5 for this reason.)

I will first try with Qt 5.4.2 (the latest stable 5.4) and, if we still have issues, try with the new Qt 5.5 - maybe we'll get lucky!

**Comment by asmaloney** [comment] 2016-04-24 18:02
@mankoff Could you please try this with the 2.7 release and close this issue if it's working for you?

**Comment by mankoff** [comment] 2016-04-24 19:54
Doesn't work and some significant new bugs.

0) Point resizing *does* work.

1) Can't select any points at all, whether "Display Options > Other Options > Try to load no GPU" is checked or not

2) Point List Picking is inactive, so I can't test this.

3) When loading a file, it is positioned with the center in the upper right corner of the screen, not centered. It also moves there if I re-center with the "1:1" toolbar icon. Even if I manually pan it to center, when I zoom, the zooming only goes to the upper right corner, not the screen center or the new location of the object after I pan it.

4) If I drag a toolbar to reposition it, the entire CC window shrinks to 1/4th of my monitor and jumps all over the place.

Hard to use this version, so there may be other issues I don't see after a few minutes.

**Comment by asmaloney** [comment] 2016-04-24 21:49
So I split out the four new issues (in the future please submit separate issues so we can manage them better).

I cannot reproduce the main issue here:

> When selecting a point, a point far from where I click is selected

I'm wondering if there's something strange with the model you're working with?

**Comment by mankoff** [comment] 2016-04-24 22:40
I just trashed my CC prefs `~/Library/Preferences/CloudCompare.plist` and `~/Library/Preferences/com.cccorp.CloudCompare.plist`. Things mostly the same. I'll reply to other tickets individually.

**Comment by asmaloney** [comment] 2016-11-18 21:14
@mankoff I think this issue was properly parsed into the four above (though we know some are still a problem).  Can we close this one?

**Comment by asmaloney** [comment] 2016-12-17 15:09
Think this was solved with the high DPI fixes from @dgirardeau.

Please create new issues if you find any.

**Closed by asmaloney** 2016-12-17 15:09 UTC
